@jwt = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc1MDA0OTMwMCwiZXhwIjoxNzUwMDkyNTAwfQ.02q5ywhQyvfK-BB6EFXKSb-Emgyg-GsXNNDbvr00xbk"

### 회원가입
POST http://localhost:4000/sign-up
Content-Type: application/json

{
    "email": "test1@example.com",
    "password": "123456789",
    "nickname": "test1"
}

### 로그인 -> 토큰 발급
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "test1@example.com",
    "password": "123456789"
}

### 전체 게시글 조회
GET http://localhost:4000/posts
Content-Type: application/json
Authorization: Bearer {{jwt}}

### 특정 게시글 조회
GET http://localhost:4000/posts/1

### 게시글 생성
POST http://localhost:4000/posts
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "title2",
  "content": "This is title2"
}

### 게시글 수정
PUT http://localhost:4000/posts/3
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "title2",
  "content": "This is title2-1"
}

### 게시글 삭제
DELETE http://localhost:4000/posts/3
Content-Type: application/json
Authorization: Bearer {{jwt}}
